#Connect DB
spring:
  config:
    import: env.properties
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/railwayticketreservationdb
    username: DB_USERNAME
    password: DB_PASS
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: EMAIL
    password: MAILSENDER_PASS
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.starttls.enable: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false