#Connect DB
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://containers-us-west-131.railway.app:6437/railwayticketreservationdb
    username: root
    password: PUvkRUkS9tumpUAakgiH
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hophuocduy261020@gmail.com
#    password: phamynnfusgajjwb
    password: phamynnfusgajjwb
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.starttls.enable: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jwt:
    secret: 2646294A404E635266556A586E3272357538782F413F442A472D4B6150645367
    jwtExpirationTime: 43200000
logging:
  level:
    org.springframework.security: TRACE